tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "on-primary-fixed-variant": "#6d3a00",
                        "error-container": "#ffdad6",
                        "surface-container-low": "#f3f3f4",
                        "secondary": "#056e00",
                        "secondary-fixed": "#8dfc75",
                        "inverse-on-surface": "#f0f1f1",
                        "error": "#ba1a1a",
                        "outline": "#887364",
                        "outline-variant": "#dbc2b0",
                        "on-primary": "#ffffff",
                        "surface-container": "#eeeeee",
                        "on-secondary": "#ffffff",
                        "secondary-container": "#8dfc75",
                        "on-error": "#ffffff",
                        "on-tertiary-container": "#3036a0",
                        "on-primary-fixed": "#2e1500",
                        "on-tertiary-fixed-variant": "#3239a3",
                        "surface-container-lowest": "#ffffff",
                        "primary-fixed-dim": "#ffb77a",
                        "on-background": "#1a1c1c",
                        "primary-fixed": "#ffdcc2",
                        "tertiary": "#4b53bc",
                        "inverse-primary": "#ffb77a",
                        "surface-container-highest": "#e2e2e2",
                        "primary-container": "#ff9933",
                        "primary": "#8f4e00",
                        "surface-bright": "#f9f9f9",
                        "surface-container-high": "#e8e8e8",
                        "on-secondary-fixed-variant": "#035300",
                        "on-primary-container": "#693800",
                        "inverse-surface": "#2f3131",
                        "on-tertiary-fixed": "#00006e",
                        "on-tertiary": "#ffffff",
                        "background": "#f9f9f9",
                        "surface-variant": "#e2e2e2",
                        "tertiary-fixed-dim": "#bfc2ff",
                        "surface-dim": "#dadada",
                        "on-surface": "#1a1c1c",
                        "surface": "#f9f9f9",
                        "on-error-container": "#93000a",
                        "tertiary-fixed": "#e0e0ff",
                        "on-secondary-fixed": "#012200",
                        "tertiary-container": "#a5abff",
                        "secondary-fixed-dim": "#72de5c",
                        "surface-tint": "#8f4e00",
                        "on-surface-variant": "#554336",
                        "on-secondary-container": "#067500"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.25rem",
                        "lg": "0.5rem",
                        "xl": "0.75rem",
                        "full": "9999px"
                    },
                    "spacing": {
                        "container-max": "1200px",
                        "gutter": "24px",
                        "margin-desktop": "48px",
                        "unit": "8px",
                        "margin-mobile": "16px",
                        "section-gap": "80px"
                    },
                    "fontFamily": {
                        "body-lg": ["Inter"],
                        "display-lg": ["Poppins"],
                        "title-sm": ["Poppins"],
                        "body-md": ["Inter"],
                        "headline-md": ["Poppins"],
                        "headline-md-mobile": ["Poppins"],
                        "label-caps": ["Inter"],
                        "display-lg-mobile": ["Poppins"]
                    },
                    "fontSize": {
                        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
                        "display-lg": ["48px", { "lineHeight": "1.2", "fontWeight": "700" }],
                        "title-sm": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
                        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
                        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
                        "headline-md-mobile": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
                        "label-caps": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
                        "display-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }]
                    }
                }
            }
        }